language: csharp
install: true
mono: none
dotnet: 2.1.502
addons:
  sonarcloud:
     organization: "controlme"
jobs:
  include:
    - stage: code_analysis
      script:
        - sonar-scanner
    - stage: build
      script:
        - cd ControlMe.WebApi
        - dotnet clean
        - dotnet restore
        - dotnet build --configuration Release --no-restore
    - stage: deploy
      script: skip
      deploy:
        provider: azure_web_apps
        verbose: true
        on:
            all_branches: true