jobs:
    dist: trusty
    install: true
    language: csharp
    mono: none
    dotnet: 2.1.502
    addons:
        sonarcloud:
            organization: "controlme"
    include:
        - stage: analyze_code
        script: sonar-scanner
        - stage: build
        script: cd ControlMe.WebApi