language: csharp
mono: none
dotnet: 2.1.502
addons:
    sonarcloud:
        organization: "controlme"
script:
    - sonar-scanner
    - cd ControlMe.WebApi
    - dotnet clean
    - dotnet restore
    - dotnet build
deploy:
    provider: azure_web_apps
    