dist: trusty
language: csharp
mono: none
dotnet: 2.1.502
addons:
    sonarcloud:
        organization: "controlme"
        token:
            secure: "f1131bcabbe295ac9db6c4321b6cb334c35f909d"
script:
    - sonar-scanner
    - cd ControlMe.WebApi
    - dotnet clean
    - dotnet restore
    - dotnet build
deploy:
    provider: azure_web_apps
    verbose: true
    username: "controlme\\usr_sluciano"
    password: "Marie2015"
    site: "controlme"
    on:
        all_branches: true
    