// <auto-generated />
using System;
using ControlMe.WebApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControlMe.WebApi.DataAccess.Migrations
{
    [DbContext(typeof(ControlMeDatabaseContext))]
    [Migration("20190708005204_DatabaseInitialization")]
    partial class DatabaseInitialization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControlMe.WebApi.DataAccess.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("ExecutionDate");

                    b.Property<bool>("Fixed");

                    b.Property<Guid?>("TransactionSourceId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("TransactionSourceId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ControlMe.WebApi.DataAccess.Entities.Income", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("ExecutionDate");

                    b.Property<bool>("Fixed");

                    b.Property<Guid?>("TransactionSourceId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("TransactionSourceId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("ControlMe.WebApi.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Source");
                });

            modelBuilder.Entity("ControlMe.WebApi.DataAccess.Entities.Expense", b =>
                {
                    b.HasOne("ControlMe.WebApi.Source", "TransactionSource")
                        .WithMany()
                        .HasForeignKey("TransactionSourceId");
                });

            modelBuilder.Entity("ControlMe.WebApi.DataAccess.Entities.Income", b =>
                {
                    b.HasOne("ControlMe.WebApi.Source", "TransactionSource")
                        .WithMany()
                        .HasForeignKey("TransactionSourceId");
                });
#pragma warning restore 612, 618
        }
    }
}
